### ISSUE TITLE
Safari warning appearing in Chrome

### ISSUE THREAD

**Issue by stocktons** [nativesintech/thislandistand.app#18]
Chrome Version 96.0.4664.110 
App sticks on loading page and displays Safari warning

**Comment by RussWilkie** [comment]
Taking a look at this issue. I found the way to remove the Safari warning from appearing on Chrome browsers is to update the filtering in **components/Main.tsx** file on **line 26**:
`O.filter((a) => /safari/i.test(a) && !/chrom\w+\//i.test(a)),`
I heard this may still be a problem with ios devices using Chrome browsers, as Chrome acts as a wrapper for Safari on Apple devices. I was not able to confirm this out with my current set-up.

@stocktons I was not able to mimic the loading page sticking issue though. I was only experiencing this issue if I did not allow location accessibility. Are you experiencing this loading after clicking allow?

**Comment by RussWilkie** [comment]
Created a Pull Request for this:
https://github.com/nativesintech/thislandistand.app/pull/21

@arecvlohe I'm not seeing you as an available reviewer in the PR. I saw you seem to be the only contributor to this repo, so giving you a tag. Apologies if I'm not following the contribution processes, I was unable to find any documentation on how to contribute to this repo

**Comment by stocktons** [comment]
@RussWilkie sorry for the delay in response. Thanks for finding a good solution! Yes, it was location services being off that was messing with the loading. I would suggest adding a message to users along with "Loading..." I'll make a PR with that addition.

**Comment by arecvlohe** [comment]
@RussWilkie Thanks for providing a solution. I'll take a look soon.

**Comment by arecvlohe** [comment]
Solved in #22
